# Generated by Django 5.2.6 on 2025-09-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_card_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='category',
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='cards', to='api.category'),
        ),
    ]
