# Generated by Django 5.2.6 on 2025-09-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_card_category_card_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='card',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
